dist:
  xenial

sudo:
  false

language:
  python

python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  # https://github.com/tobgu/pyrsistent/issues/208
  - pip install --upgrade pip
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

jobs:
  include:
    - stage: release
      if: tag IS present
      python: 3.8
      deploy:
        provider: pypi
        user: roll
        distributions: sdist bdist_wheel
        skip_cleanup: true
        on:
          tags: true
        password:
          secure: WofAaa4zh8wXQWLjfm8w0IxxGZUCgMRBsqhUoUJLLvMraGNUMV9hHp9DS7XfCGvlrIUQXHpTvgM1t7pUIJRE/PqTQR8FOocqN+ZmH8BqDDXsIoyQexDUtWDDbFXNaKJ4D2efIdoqWwDc9do2zt+EWRkt4xQcnbm7O6GUXlxUyTI=
